### ISSUE TITLE
Shape is inverted in the xml file

### ISSUE THREAD

**Issue by krishnakanthnakka** [hamzarawal/cityscapes_to_voc#1]
Can you please check if the width and height are inverted in the XML file.

**Comment by hamzarawal** [comment]
Hi Krishna,
Thank you for pointing it out. Yes, the shape is indeed saved in reverse order. In my case, this was just an additional information and was not used any further, thus couldn't notice it.
Anyways, you can just reverse the shape by reversing the arguments to the Writer function:
```diff
-writer = Writer(img_path,img_shape[0], img_shape[1])
+writer = Writer(img_path,img_shape[1], img_shape[0])
```

**Comment by krishnakanthnakka** [comment]
Thanks:)
